environment: dev
api_server:
    dev:
        host: '127.0.0.1'
        port: '8080'
        
database:
    dev: &db_defaults
        conn_string: 'sqlite:///testdb.db'
        #conn_string: 'mysql://test:test@localhost/testdb'
    staging: 
        <<: *db_defaults
    prod: 
        <<: *db_defaults
